name: PR Check

on:
  - pull_request

jobs:
  check:
    runs-on: runner
    defaults:
      run:
        shell: bash
        working-directory: ./app-demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependecies
        run: |
          pip3 install -r requirements.txt

      - name: Run tests
        run: |
          pytest test/test.py
